package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.io.BufferedReader;
import java.io.File;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.net.Socket;

import javafx.event.ActionEvent;

import javafx.scene.control.TextArea;

import javafx.scene.layout.GridPane;
import javafx.stage.FileChooser;

public class Control {
	@FXML
	private TextField hostnameV;
	@FXML
	private TextField portV;
	@FXML
	private Button btnConnextion;
	@FXML
	private GridPane body;
	@FXML
	private TextArea textArea1;
	@FXML
	private TextArea textArea2;
	@FXML
	private Button b1;

	
	
	
	Socket socket;
    private static BufferedReader br;
    private static PrintStream ps;

	// Event Listener on MenuItem.onAction
	@FXML
	public void openFile(ActionEvent event) {
		FileChooser fileChooser = new FileChooser();

        //only allow text files to be selected using chooser
        fileChooser.getExtensionFilters().add(
                new FileChooser.ExtensionFilter("Text files (*.txt)", "*.txt")
        );

        //set initial directory somewhere user will recognise
        fileChooser.setInitialDirectory(new File(System.getProperty("user.home")));

        //let user select file
        File fileToLoad = fileChooser.showOpenDialog(null);
        
        if (fileToLoad != null) {
        	System.out.println("file = "+fileToLoad.getPath());
        }
        else {
        	System.out.println("file = null");
        }
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void saveFile(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnConnextion].onAction
	@FXML
	public void connexion(ActionEvent event) {
		int port = Integer.parseInt(portV.getText().toString());
    	String host = hostnameV.getText();
    	
    	try {
			socket = new Socket(host, port);
	    	ps = new PrintStream(socket.getOutputStream());
	    	br = new BufferedReader(new InputStreamReader(socket.getInputStream()));
	    	
	    	body.setDisable(false);
	    	
    	}  catch (Exception e) {
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#b1].onAction
	@FXML
	public void b1_exec(ActionEvent event) {
		System.out.println("b1_exec");
    	System.out.println("textArea1 = "+textArea1.getText());
	}
}